### ISSUE TITLE
JSON API

### ISSUE THREAD

**Issue by jeroenhd** [qtwyeuritoiy/CandyBox#2]
Hi! I just noticed your project (am slowly working on a comic reading app myself) and I noticed you seem to be parsing HTML for most of the content.

I'm not sure, but you might get better performance out of the Candybooru JSON API.

Take a look:
- [https://www.bittersweetcandybowl.com/app/json/check](https://www.bittersweetcandybowl.com/app/json/check)
- [https://www.bittersweetcandybowl.com/app/json/gallery-0](https://www.bittersweetcandybowl.com/app/json/gallery-0)

The downside of the JSON API is that it doesn't support comments. It might be an easier way to pull down the submission list though. It's also more reliable, since it doesn't depend on static HTML IDs.

**Comment by cherryband** [comment]
Hi! Thank you for having interest in this project. Honestly I didn't had a motivation to develop this year so I was in the verge of abandoning the project (and have abandoned for past 4 months).

I have known the existence of the JSON feed, but the scope it can cover seems very limited. I was planning to implement search feature directly into the app(you can see that in the getThumbnails() method in CandyBooryMainPageParser; it contains a if-statement that detects if the content is not found, which would never happen in "Recents" tab), which requires sending query. The JSON API only seems to provide recent submissions. Also, parsing the HTML directly doesn't seem to be a performance bottleneck.
So considering the scope, I decided that using JSON API is not worth the time.

Again, thank you for having interest in my project and reviewing my code.
